import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { basename, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { assertVersion, REQUIRED_ASSETS, runGh, syncHomepage, THEME_REPOSITORY } from './sync-homepage.mjs';

const projectRoot = fileURLToPath(new URL('../', import.meta.url));
const valueFlags = new Set(['--title', '-t', '--notes', '-n', '--notes-file', '-F', '--target', '--notes-start-tag', '--discussion-category']);
const booleanFlags = new Set(['--verify-tag', '--generate-notes', '--notes-from-tag', '--fail-on-no-commits', '--latest']);
const notesFlags = new Set(['--notes', '-n', '--notes-file', '-F', '--generate-notes', '--notes-from-tag']);
const digest = bytes => createHash('sha256').update(bytes).digest('hex');

/** Preserve each argument exactly while refusing repository/draft overrides. */
export function parseReleaseArguments(args) {
  const assets = [];
  let hasNotes = false;
  for (let index = 0; index < args.length; index += 1) {
    const argument = args[index];
    if (!argument.startsWith('-')) {
      assets.push(argument.split('#', 1)[0]);
      continue;
    }
    const separator = argument.indexOf('=');
    const flag = separator < 0 ? argument : argument.slice(0, separator);
    const inlineValue = separator < 0 ? undefined : argument.slice(separator + 1);
    if (valueFlags.has(flag)) {
      const value = inlineValue ?? args[++index];
      if (!value || ((flag === '--notes-file' || flag === '-F') && value === '-')) {
        throw new Error(`${flag} requires a value; stdin release notes are not supported.`);
      }
    } else if (booleanFlags.has(flag)) {
      if (inlineValue !== undefined && !['true', 'false'].includes(inlineValue)) throw new Error(`Invalid boolean option: ${argument}`);
      if (flag === '--verify-tag' && inlineValue === 'false') throw new Error('Published tags must be verified; --verify-tag=false is not allowed.');
    } else {
      throw new Error(`Unsupported release option: ${flag}. Repository overrides, drafts and prereleases are not allowed by this stable release command.`);
    }
    if (notesFlags.has(flag) && inlineValue !== 'false') hasNotes = true;
  }
  if (!hasNotes) throw new Error('Provide --notes-file, --notes, --notes-from-tag or --generate-notes for a noninteractive release.');
  return assets;
}

export async function validateReleaseAssets(version, args, { root = projectRoot, cwd = process.cwd() } = {}) {
  assertVersion(version);
  const paths = parseReleaseArguments(args);
  const assets = new Map();
  for (const path of paths) {
    const name = basename(path);
    if (![...REQUIRED_ASSETS, `Tsukuyomi-${version}.zip`].includes(name)) throw new Error(`Unexpected release attachment: ${name}`);
    if (assets.has(name)) throw new Error(`Duplicate release asset: ${name}`);
    assets.set(name, await readFile(resolve(cwd, path)));
  }
  for (const name of REQUIRED_ASSETS) {
    if (!assets.get(name)?.length) throw new Error(`Supply the existing ${name} release attachment; no assets are generated by this command.`);
  }
  const localManifestBytes = await readFile(resolve(root, 'manifest.json'));
  const manifest = JSON.parse(localManifestBytes);
  const pkg = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'));
  if (manifest.name !== 'Tsukuyomi' || manifest.version !== version || pkg.version !== version) {
    throw new Error('Release version must match the local Tsukuyomi manifest and package version.');
  }
  if (!assets.get('manifest.json').equals(localManifestBytes)
      || !assets.get('theme.css').equals(await readFile(resolve(root, 'theme.css')))) {
    throw new Error('Release manifest.json and theme.css must exactly match the checked local build.');
  }
  const checksums = new Map();
  for (const line of assets.get('SHA256SUMS.txt').toString('utf8').trim().split(/\r?\n/)) {
    const match = /^([a-f\d]{64}) {2}([^/\\]+)$/.exec(line);
    if (!match || checksums.has(match[2])) throw new Error('SHA256SUMS.txt contains an invalid or duplicate asset entry.');
    checksums.set(match[2], match[1]);
  }
  for (const [name, bytes] of assets) {
    if (name !== 'SHA256SUMS.txt' && checksums.get(name) !== digest(bytes)) throw new Error(`Checksum missing or mismatched for ${name}.`);
  }
  for (const name of checksums.keys()) {
    if (name === 'SHA256SUMS.txt' || !assets.has(name)) throw new Error(`Checksum names an attachment not supplied: ${name}`);
  }
}

export async function publishRelease(version, args, { run = runGh, root = projectRoot, cwd = process.cwd() } = {}) {
  await validateReleaseAssets(version, args, { root, cwd });
  await run(['release', 'create', version, ...args, '--verify-tag', '--repo', THEME_REPOSITORY], { cwd });
  try {
    return await syncHomepage(version, { run });
  } catch (cause) {
    throw new Error(`Release ${version} has been created; do not recreate it. Website sync did not complete. After fixing the reported issue, retry: npm run sync:site -- ${version}\n${cause.message}`, { cause });
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const [version, ...args] = process.argv.slice(2);
    const result = await publishRelease(version, args);
    console.log(`Published Tsukuyomi ${result.version} and requested its irop.one deployment. Check the website workflow for completion.`);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
